### ISSUE TITLE
Error digital envelope routines::unsupported

### ISSUE THREAD

**Issue by rsokolov06** [cypress-io/cypress-realworld-testing-blog#10]
Hello,

I have just cloned the repo and follow guidelines in the README.

When starting local server with yarn dev, I get the following:

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at BulkUpdateDecorator.hashFactory (C:\Users\romas\Projects\cypress-realworld-testing-blog\node_modules\next\dist\compiled\webpack\bundle5.js:138971:18)
    at BulkUpdateDecorator.update (C:\Users\romas\Projects\cypress-realworld-testing-blog\node_modules\next\dist\compiled\webpack\bundle5.js:138872:50)
    at OriginalSource.updateHash (C:\Users\romas\Projects\cypress-realworld-testing-blog\node_modules\next\dist\compiled\webpack-sources3\index.js:1:10264)
    at NormalModule._initBuildHash (C:\Users\romas\Projects\cypress-realworld-testing-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68468:17)
    at handleParseResult (C:\Users\romas\Projects\cypress-realworld-testing-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68534:10)
    at C:\Users\romas\Projects\cypress-realworld-testing-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68628:4
    at processResult (C:\Users\romas\Projects\cypress-realworld-testing-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68343:11) 
    at C:\Users\romas\Projects\cypress-realworld-testing-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68407:5
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at BulkUpdateDecorator.hashFactory (C:\Users\romas\Projects\cypress-realworld-testing-blog\node_modules\next\dist\compiled\webpack\bundle5.js:138971:18)
    at BulkUpdateDecorator.update (C:\Users\romas\Projects\cypress-realworld-testing-blog\node_modules\next\dist\compiled\webpack\bundle5.js:138872:50)
    at OriginalSource.updateHash (C:\Users\romas\Projects\cypress-realworld-testing-blog\node_modules\next\dist\compiled\webpack-sources3\index.js:1:10264)
    at NormalModule._initBuildHash (C:\Users\romas\Projects\cypress-realworld-testing-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68468:17)
    at handleParseResult (C:\Users\romas\Projects\cypress-realworld-testing-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68534:10)
    at C:\Users\romas\Projects\cypress-realworld-testing-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68628:4
    at processResult (C:\Users\romas\Projects\cypress-realworld-testing-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68343:11) 
    at C:\Users\romas\Projects\cypress-realworld-testing-blog\node_modules\next\dist\compiled\webpack\bundle5.js:68407:5
Waiting for the debugger to disconnect...
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);

Please advise how to resolve this.

Thanks in advance
Roman

**Comment by yarmakx** [comment]
@rsokolov06 you can try to downgrade your node version to 16. It worked for me
